alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = false
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = true
enableSpaceControl = false
enableSpaceControlAnimations = true
enableSwipeGestures = true
enableWorkspaceTransitions = false
focusFrontmostWindow = false
focusNextWorkspaceWindow = 'opt+h'
focusPreviousWorkspaceWindow = 'opt+a'
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
pipScreenCornerOffset = 15
runScriptOnLaunch = ''
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = 'sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE" DISPLAY="$DISPLAY"'
showFloatingNotifications = true
showMenuBarTitle = true
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlMaxColumns = 6
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'none'
swipeLeft4FingerAction = 'previousWorkspace'
swipeRight3FingerAction = 'none'
swipeRight4FingerAction = 'nextWorkspace'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchToRecentWorkspace = 'opt+tab'
toggleTheFocusedAppFloating = 'opt+f'
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999