git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never -s
gui:
  # Fraction of the total screen width to use for the left side section. You may want to pick a small number (e.g. 0.2) if you're using a narrow screen, so that you can see more of the main section.
  # Number from 0 to 1.0.
  sidePanelWidth: 0.25

# Keybindings
keybinding:
  universal:
    prevItem-alt: a
    nextItem-alt: h
    scrollLeft: P
    scrollRight: E
    prevBlock-alt: p
    nextBlock-alt: e
    edit: l
    openFile: o
    scrollUpMain-alt1: A
    scrollDownMain-alt1: H

    # 'Files' appended for legacy reasons
    pushFiles: K

    # 'Files' appended for legacy reasons
    pullFiles: k
  status:
    allBranchesLogGraph: A
  files:
    toggleStagedAll: "'"
    amendLastCommit: '"'
  branches:
    pushTag: K
  commits:
    amendToCommit: '"'
    resetCommitAuthor: "'"
    pickCommit: k
  main:
    toggleSelectHunk: "'"
    editSelectHunk: L
