theme = "kanagawa"

[editor]
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# k = "move_char_left"
# h = "move_visual_line_down"
# a = "move_visual_line_up"
# e = "move_char_right"
# l = "move_next_word_end"
# L = "move_next_long_word_end"
# "'" = "append_mode"
# '"' = "insert_at_line_end"
# j = "select_register"
# D = "delete_selection_noyank"
# C = "change_selection_noyank"
# q = "record_macro"
# Q = "replay_macro"
V = ["select_mode", "extend_to_line_bounds"]
# x = "select_regex"
# X = "split_selection"
s = "goto_word"

[keys.select]
# p = "move_char_left"
# h = "move_visual_line_down"
# h = "extend_line_below"
# a = "move_visual_line_up"
# e = "move_char_right"
# l = "move_next_word_end"
# L = "move_next_long_word_end"
# A = "keep_selections"
